# Javascript Node CircleCI 2.0 configuration file
# testing ci
defaults: &defaults
  docker:
    - image: circleci/node:latest
    - image: circleci/mysql:8.0.4

  working_directory: ~/MERNolithic_sql

version: 2
jobs:
  build:
    <<: *defaults

    steps:
      - checkout

      - restore_cache:
          name: Restore backend/general packages
          keys:
            - v5-dependencies-{{.Branch}}-{{ checksum "package.json" }}
            - v5-dependencies-{{.Branch}}-
            - v5-dependencies-

      - run:
          name: Install general dependencies
          command: npm install

      - save_cache:
          name: Save general packages cache
          paths:
            - ~/node_modules
          key: v5-dependencies-{{.Branch}}-{{ checksum "package.json" }}

      - restore_cache:
          name: Restore frontend packages
          keys:
            - v5-dependencies-{{.Branch}}-{{ checksum "frontend/package.json" }}
            - v5-dependencies-{{.Branch}}-
            - v5-dependencies-

      - run:
          name: Install frontend packages
          command: cd frontend && npm install

      - save_cache:
          paths:
            - ~/frontend/node_modules
          key: v5-dependencies-{{.Branch}}-{{ checksum "frontend/package.json" }}

      - restore_cache:
          name: Restore backend packages
          keys:
            - v5-dependencies-{{.Branch}}-{{ checksum "backend/package.json" }}
            - v5-dependencies-{{.Branch}}-
            - v5-dependencies-

      - run:
          name: Install backend packages
          command: cd backend && npm install

      - save_cache:
          paths:
            - ~/backend/node_modules
          key: v5-dependencies-{{.Branch}}-{{ checksum "backend/package.json" }}

      - run:
          name: Build frontend
          command: cd frontend && yarn build

      - persist_to_workspace:
          root: ~/
          paths:
            - MERNolithic_sql
            - .cache
  # js_unit_tests:
  #   <<: *defaults
  #   steps:
  #     - attach_workspace:
  #         at: ~/
  #     - run:
  #         name: Frontend Unit tests
  #         command: |
  #           cd client
  #           npm run test
  # backend_unit_tests:
  #   <<: *defaults
  #   steps:
  #     - attach_workspace:
  #         at: ~/
  #     - run:
  #         name: Backend Unit Tests
  #         command: npm run backend-unit-tests
  coverage_test:
    <<: *defaults
    docker:
      - image: cypress/base:8
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Run cypress tests
          command: yarn test:coverage
      - store_artifacts:
          path: coverage/lcov-report
      - store_artifacts:
          path: cypress/reports/integration/public/
  cypress_tests:
    <<: *defaults
    docker:
      - image: cypress/base:8
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Run cypress tests
          command: yarn test:create-reports
      - store_artifacts:
          path: coverage/lcov-report
      - store_artifacts:
          path: cypress/reports/integration/public/
      # - store_artifacts:
      #     path: cypress/reports/integration/public/videos
      # - store_artifacts:
      #     path: cypress/reports/integration/public/screenshots
      # - run:
      #     name: Run backend
      #     command: npm run backend
      #     background: true
      # - run:
      #     name: Run frontend
      #     command: npm run frontend
      #     background: true
      # - run:
      #     name: Run UI tests
      #     command: npm run ui-tests
  # api_tests:
  #   <<: *defaults
  #   steps:
  #     - attach_workspace:
  #         at: ~/
  #     - run:
  #         name: Run backend
  #         command: npm run backend
  #         background: true
  #     - run:
  #         name: Run local API tests
  #         command: yarn wait-on http://localhost:3001 && npm run api-tests

workflows:
  version: 2
  starter-workflow:
    jobs:
      - build
      # - coverage_test:
      #     requires:
      #       - build
      - cypress_tests:
          requires:
            - build
      # - js_unit_tests:
      #     requires:
      #       - build
      # - backend_unit_tests:
      #     requires:
      #       - build
      # - api_tests:
      #     requires:
      #       - build
      # - ui_tests:
      #     requires:
      #       - build
      # RECOMMENDED NODE config
      # version: 2.1
      # orbs:
      #   node: circleci/node@1.1.6
      # jobs:
      #   build-and-test:
      #     executor:
      #       name: node/default
      #     steps:
      #       - checkout
      #       - node/with-cache:
      #           steps:
      #             - run: npm install
      #             - run: npm test
      # workflows:
      #     build-and-test:
      #       jobs:
      #         - build-and-test
