import './style.css';
import React, { useContext } from 'react';
import { Link } from 'react-router-dom';
import { UserContext } from '../../Contexts/UserContext';
import API from '../../Utilities/API';

export default function NavTrack({ children }) {
  const { user, setUser } = useContext(UserContext);
  const logout = () => {
    API.logout().then((res) => {
      if (res.status == 200) {
        setUser({ ...user, isAuthenticated: false, isCreated: false });
      }
    });
  };
  const title = 'Application Generated by MERNolithic';

  const login = (
    <Link className='navLink' data-test='login-navlink' to='/login'>
      Login
    </Link>
  );
  const register = (
    <Link className='navLink' data-test='register-navlink' to='/register'>
      Register
    </Link>
  );
  const dashboard = (
    <Link className='navLink' to='/dashboard'>
      Dashboard
    </Link>
  );
  const logoutButton = (
    <button
      className='navLink'
      data-test='logout-button'
      onClick={() => logout()}
    >
      Logout
    </button>
  );

  const authenticatedItems = [dashboard, logoutButton];
  const notAuthenticatedItems = [login, register];

  const items = user.isAuthenticated
    ? authenticatedItems
    : notAuthenticatedItems;

  return (
    <div className='track'>
      {children}
      <h2 className='trackTitle'>{title}</h2>

      {items &&
        items.length > 0 &&
        items.map((item, i) => (
          <div className='trackItemContainer' key={i}>
            <li className='trackItem'>{item}</li>
          </div>
        ))}
    </div>
  );
}
